

try:
    print(a)
except Exception as e:
    print("something went wron please try again later")


print("hello")
